import Link from 'next/link';
import { ArrowRight, Check, ShieldAlert, Sparkles } from 'lucide-react';
import { mattresses } from '@/data/mattresses';
import { scoreMattress, SCORING_VERSION } from '@/lib/scoring/engine';
import type { SleepProfile } from '@/lib/types';

const profile: SleepProfile = { position:'side', weight:155, height:67, firmness:'medium', surfaceFeel:'medium', temperature:'neutral', motion:'couple', priority:'pressure', budget:1800, types:['hybrid','foam','innerspring'] };
const rows = mattresses.slice(0,3).map(m => ({ mattress:m, score:scoreMattress(m,profile) }));
const metrics = [['Pressure relief','pressure'],['Support & alignment','support'],['Cooling & airflow','cooling'],['Motion isolation','motion'],['Edge support','edge'],['Responsiveness','responsiveness']] as const;

export default function ComparePage(){return <main className="min-h-screen bg-[#eef4f0] text-[#092e2a] pb-24"><header className="sticky top-0 z-40 border-b border-white/60 bg-[#eef4f0]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1240px] items-center justify-between px-5 py-4 sm:px-7"><Link href="/" className="flex items-center gap-2 font-extrabold tracking-[-.04em]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#092e2a] text-white">M</span> mattress match</Link><nav className="hidden items-center gap-6 text-sm font-semibold text-[#60706b] md:flex"><Link href="/mattresses">Explore</Link><Link href="/methodology">Methodology</Link></nav><Link href="/#match" className="btn-primary !px-4 !py-2.5 text-sm">Build my profile</Link></div></header>
<section className="relative overflow-hidden"><div className="absolute -right-20 top-0 h-[520px] w-[520px] rounded-full bg-[#6ce7d6]/20 blur-3xl"/><div className="section relative pb-10 pt-16 sm:pt-24"><div className="eyebrow flex items-center gap-2"><Sparkles size={14}/> Decision view</div><div className="mt-4 grid gap-8 lg:grid-cols-[1fr_.5fr] lg:items-end"><div><h1 className="max-w-4xl text-6xl font-extrabold leading-[.88] tracking-[-.07em] sm:text-8xl">Compare the <span className="text-[#18a895]">tradeoffs.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#60706b]">See the differences that can actually change how each mattress feels for your sleep profile—not just which one has the biggest headline number.</p></div><div className="rounded-[28px] border border-white bg-white/80 p-5 shadow-sm"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#18a895]">Profile used</p><p className="mt-2 font-bold">Side sleeper · 155 lb · couple · neutral</p><p className="mt-1 text-sm text-[#73807b]">Pressure relief priority · model v{SCORING_VERSION}</p><Link href="/#match" className="mt-4 inline-flex items-center gap-2 text-sm font-extrabold text-[#0d8879]">Change profile <ArrowRight size={15}/></Link></div></div></div></section>
<section className="section pt-3"><div className="grid gap-4 md:grid-cols-3">{rows.map(({mattress,score},i)=><Link href={`/mattress/${mattress.id}`} key={mattress.id} className="group overflow-hidden rounded-[32px] border border-white bg-white shadow-[0_20px_70px_rgba(10,45,40,.07)] transition duration-500 hover:-translate-y-1"><div className="relative h-64 overflow-hidden bg-[#e2ebe6]"><img src={mattress.image} alt={`${mattress.brand} ${mattress.model}`} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]"/><div className="absolute left-4 top-4 rounded-full border border-white/40 bg-[#092e2a]/80 px-3 py-1.5 text-xs font-extrabold text-white backdrop-blur">{i===0?'Profile leader':'Alternative'}</div></div><div className="p-6"><div className="text-xs font-bold uppercase tracking-[.13em] text-[#18a895]">{mattress.brand}</div><div className="mt-1 flex items-start justify-between gap-3"><h2 className="text-2xl font-extrabold tracking-[-.04em]">{mattress.model}</h2><div className="text-right"><div className="text-3xl font-extrabold">{score.overall}</div><div className="text-[10px] font-bold uppercase tracking-wider text-[#82908a]">match</div></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-[#61716b]"><span className="rounded-full bg-[#f0f5f2] px-3 py-1.5">{mattress.type}</span><span className="rounded-full bg-[#f0f5f2] px-3 py-1.5">{mattress.firmness}/10 firmness</span></div></div></Link>)}</div></section>
<section className="section pt-8"><div className="overflow-hidden rounded-[36px] border border-white/80 bg-white shadow-[0_30px_100px_rgba(10,45,40,.09)]"><div className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-4 bg-[#092e2a] p-6 text-white"><div className="flex items-end text-xs font-bold uppercase tracking-[.15em] text-white/50">Performance</div>{rows.map(({mattress,score},i)=><div key={mattress.id} className="pl-4"><div className="text-xs font-bold uppercase tracking-[.12em] text-[#6ce7d6]">{i===0?'Profile leader · ':''}{mattress.brand}</div><div className="mt-1 text-xl font-extrabold">{mattress.model}</div><div className="mt-3 text-4xl font-extrabold tracking-[-.05em]">{score.overall}<span className="ml-1 text-xs font-semibold text-white/50">/100</span></div></div>)}</div>{metrics.map(([label,key])=><div key={key} className="grid grid-cols-4 border-b border-[#edf1ef] p-6"><div className="font-bold text-[#40554f]">{label}</div>{rows.map(({mattress,score})=><div key={mattress.id} className="pr-8"><div className="flex justify-between text-sm font-extrabold"><span>{score[key]}</span><span className="text-[#a0aaa6]">/100</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e7eeea]"><div className="h-full rounded-full bg-[#18b7a2]" style={{width:`${score[key]}%`}}/></div></div>)}</div>)}</div></div><div className="grid grid-cols-1 gap-4 bg-[#f8faf9] p-6 md:grid-cols-3">{rows.map(({mattress,score})=><div key={mattress.id}><div className="mb-2 text-xs font-extrabold uppercase tracking-[.12em] text-[#687872]">{mattress.model} · watch-outs</div>{score.risks.slice(0,2).map(r=><div key={r} className="flex gap-2 text-sm leading-6 text-[#65736e]"><ShieldAlert size={15} className="mt-1 shrink-0 text-[#b37d25]"/>{r}</div>)}</div>)}</div></div></section>
<section className="section pt-8"><div className="grid gap-5 md:grid-cols-3">{rows.map(({mattress,score},i)=><article key={mattress.id} className={`rounded-[30px] p-7 text-white ${i===0?'bg-[#092e2a]':'bg-[#123f39]'}`}><div className="text-xs font-bold uppercase tracking-[.15em] text-[#6ce7d6]">{mattress.brand}</div><h2 className="mt-2 text-2xl font-extrabold">{mattress.model}</h2><div className="mt-6 space-y-3 text-sm text-white/70">{score.reasons.slice(0,3).map(r=><p key={r} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-[#6ce7d6]"/>{r}</p>)}</div><Link href={`/mattress/${mattress.id}`} className="btn-primary mt-7 w-full !bg-white !text-[#092e2a]">Explore mattress <ArrowRight size={16}/></Link></article>)}</div></section>
<section className="section pt-8"><div className="rounded-[36px] bg-[#092e2a] p-8 text-white sm:p-12"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#6ce7d6]">Transparent by design</p><h2 className="mt-3 text-3xl font-extrabold">The comparison is only as good as the profile behind it.</h2><p className="mt-3 max-w-2xl leading-7 text-white/55">Change your sleep position, temperature preference, motion sensitivity or comfort priority and the Match Scores can change with it.</p></div><Link href="/methodology" className="btn-primary whitespace-nowrap !bg-[#6ce7d6] !text-[#092e2a]">See methodology <ArrowRight size={16}/></Link></div></div></section>
</main>}
