import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Check, AlertTriangle, ArrowUpRight, ShieldCheck, Sparkles, Thermometer, Waves, Moon, Gauge } from 'lucide-react';
import { mattresses } from '@/data/mattresses';
import { scoreMattress } from '@/lib/scoring/engine';
import type { SleepProfile } from '@/lib/types';

export function generateStaticParams(){return mattresses.map(m=>({slug:m.id}))}

const profile: SleepProfile = { position:'side', weight:155, height:67, firmness:'medium', surfaceFeel:'medium', temperature:'neutral', motion:'couple', priority:'pressure', budget:1800, types:['hybrid','foam','innerspring'] };

export default async function MattressPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const m=mattresses.find(x=>x.id===slug); if(!m)notFound();
 const score=scoreMattress(m,profile);
 const metrics=[['Pressure relief',m.pressure, Waves],['Support & alignment',m.support, Gauge],['Cooling & airflow',m.cooling, Thermometer],['Motion isolation',m.motion, Moon],['Edge support',m.edge, ShieldCheck],['Responsiveness',m.responsiveness, Sparkles]] as const;
 return <main className="min-h-screen bg-[#f3f7f4] text-[#092e2a]">
  <nav className="sticky top-0 z-40 border-b border-white/60 bg-[#f3f7f4]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-[1240px] items-center justify-between px-5 py-4 sm:px-7"><Link href="/" className="flex items-center gap-2 font-extrabold tracking-[-.04em]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#092e2a] text-white">M</span> mattress match</Link><div className="hidden items-center gap-6 text-sm font-semibold text-[#66736e] md:flex"><Link href="/mattresses">Explore</Link><Link href="/compare">Compare</Link><Link href="/methodology">Methodology</Link></div><Link href="/#match" className="btn-primary !px-4 !py-2.5 text-sm">Find my match <ArrowRight size={15}/></Link></div></nav>
  <section className="relative overflow-hidden bg-[#092e2a] text-white"><div className="absolute -left-32 top-0 h-[420px] w-[420px] rounded-full bg-[#39d8c2]/15 blur-3xl"/><div className="absolute -right-24 bottom-0 h-[500px] w-[500px] rounded-full bg-[#39d8c2]/10 blur-3xl"/><div className="relative mx-auto grid max-w-[1240px] gap-10 px-5 py-14 sm:px-7 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-20"><div><Link href="/mattresses" className="inline-flex items-center gap-2 text-sm font-semibold text-white/55 transition hover:text-white">← All mattresses</Link><div className="mt-10 flex flex-wrap gap-2"><span className="rounded-full border border-[#6ce7d6]/25 bg-[#6ce7d6]/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.12em] text-[#6ce7d6]">{m.type}</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/65">{m.firmness}/10 firmness</span></div><p className="mt-7 text-sm font-bold uppercase tracking-[.18em] text-[#6ce7d6]">{m.brand}</p><h1 className="mt-2 text-[clamp(3rem,6vw,5.7rem)] font-extrabold leading-[.92] tracking-[-.065em]">{m.model}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">A closer look at how this mattress performs across the dimensions that matter to real sleepers.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#match-score" className="btn-primary !bg-[#6ce7d6] !text-[#092e2a]">See your match <ArrowRight size={17}/></a><a href="#retailer" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-5 py-3.5 text-sm font-bold text-white backdrop-blur transition hover:bg-white/10">Retailer options <ArrowUpRight size={16}/></a></div></div><div className="relative"><div className="absolute -inset-4 rounded-[40px] bg-[#6ce7d6]/10 blur-2xl"/><div className="relative overflow-hidden rounded-[38px] border border-white/10 bg-white/5 p-2 shadow-2xl shadow-black/20"><img src={m.image} alt={`${m.brand} ${m.model}`} className="h-[390px] w-full rounded-[31px] object-cover transition duration-700 hover:scale-[1.02]"/><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between rounded-2xl border border-white/15 bg-[#092e2a]/70 p-4 backdrop-blur-xl"><div><p className="text-xs font-semibold text-white/50">Reference price</p><p className="mt-1 text-2xl font-extrabold">${m.price.toLocaleString()}</p></div><div className="text-right"><p className="text-xs font-semibold text-white/50">Trial</p><p className="mt-1 font-bold">{m.trial}</p></div></div></div></div></div></section>
  <section id="match-score" className="mx-auto max-w-[1240px] px-5 py-10 sm:px-7 lg:py-16"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="relative overflow-hidden rounded-[34px] bg-[#6ce7d6] p-7 sm:p-9"><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-white/20 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><span className="text-xs font-extrabold uppercase tracking-[.16em] text-[#146e64]">Your match</span><Sparkles size={19} className="text-[#146e64]"/></div><div className="mt-7 flex items-end gap-2"><strong className="text-[7rem] font-extrabold leading-none tracking-[-.08em]">{score.overall}</strong><span className="mb-3 text-lg font-bold text-[#146e64]">/100</span></div><p className="mt-4 max-w-sm text-[#145c55]">For a side sleeper who prioritizes pressure relief, this is how the current scoring model evaluates the fit.</p><div className="mt-7 rounded-2xl bg-[#092e2a]/8 p-4 text-sm font-semibold text-[#145c55]">Personalized profile · side sleeper · 155 lb · couple · pressure relief</div></div></div><div className="rounded-[34px] border border-[#dce6e1] bg-white p-7 shadow-[0_20px_70px_rgba(10,45,40,.06)] sm:p-9"><div className="flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#178f80]">Performance map</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-.04em]">What the score is made of</h2></div><span className="hidden text-xs font-semibold text-[#8a9691] sm:block">/100 each</span></div><div className="mt-7 grid gap-5 sm:grid-cols-2">{metrics.map(([label,value,Icon])=><div key={label} className="rounded-2xl bg-[#f4f7f5] p-4"><div className="flex items-center gap-2 text-sm font-bold"><Icon size={16} className="text-[#18a895]"/>{label}<b className="ml-auto">{value}</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#dfe9e4]"><div className="h-full rounded-full bg-[#18b7a2]" style={{width:`${value}%`}}/></div></div>)}</div></div></div></section>
  <section className="mx-auto max-w-[1240px] px-5 pb-10 sm:px-7"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-[34px] bg-[#092e2a] p-7 text-white sm:p-9"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#6ce7d6]">Why it fits</p><h2 className="mt-3 text-3xl font-extrabold">The upside for your profile</h2><div className="mt-7 space-y-4">{score.reasons.map(reason=><div key={reason} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-white/75"><Check size={18} className="mt-0.5 shrink-0 text-[#6ce7d6]"/>{reason}</div>)}</div></div><div className="rounded-[34px] border border-[#eadfd2] bg-[#fffaf4] p-7 sm:p-9"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#a56b36]">Tradeoffs</p><h2 className="mt-3 text-3xl font-extrabold">Know before you buy</h2><div className="mt-7 space-y-4">{m.risks.length?m.risks.map(risk=><div key={risk} className="flex gap-3 rounded-2xl border border-[#eadfd2] bg-white/70 p-4 text-[#67594c]"><AlertTriangle size={18} className="mt-0.5 shrink-0 text-[#b7793c]"/>{risk}</div>):<p className="text-[#67594c]">No major risk flags are currently recorded for this mattress.</p>}</div></div></div></section>
  <section className="mx-auto max-w-[1240px] px-5 py-10 sm:px-7"><div className="rounded-[36px] border border-[#dce6e1] bg-white p-7 shadow-[0_20px_70px_rgba(10,45,40,.05)] sm:p-10"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#178f80]">Real-world notes</p><h2 className="mt-3 text-3xl font-extrabold">Review highlights</h2><p className="mt-3 leading-7 text-[#687671]">Useful themes surfaced from the normalized review dataset. They complement the score rather than replacing it.</p></div><div className="grid gap-3 sm:grid-cols-2">{m.highlights.map((highlight,i)=><div key={highlight} className="rounded-2xl bg-[#f4f7f5] p-5"><span className="text-xs font-bold text-[#9aa6a1]">0{i+1}</span><p className="mt-2 font-semibold leading-6 text-[#344842]">{highlight}</p></div>)}</div></div></div></section>
  <section id="retailer" className="mx-auto max-w-[1240px] px-5 pb-20 sm:px-7"><div className="relative overflow-hidden rounded-[38px] bg-[#092e2a] p-7 text-white sm:p-10"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-[#6ce7d6]/10 blur-3xl"/><div className="relative grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#6ce7d6]"><ShieldCheck size={15}/> Verified destination policy</div><h2 className="mt-3 text-3xl font-extrabold">Ready to check the current offer?</h2><p className="mt-3 max-w-2xl text-white/60">Retailer links are only published when verified affiliate destinations are available. No fabricated destinations.</p><p className="mt-4 text-sm text-white/45">Reference: ${m.price.toLocaleString()} · {m.trial} trial · {m.warranty} warranty</p></div><button type="button" className="btn-primary whitespace-nowrap !bg-[#6ce7d6] !text-[#092e2a]">Retailer link coming soon <ArrowRight size={16}/></button></div></div></section>
 </main>
}