import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, ShieldAlert, Wind, Moon, Layers3, ExternalLink } from 'lucide-react';
import { mattresses } from '@/data/mattresses';
import { scoreMattress } from '@/lib/scoring/engine';
import type { SleepProfile } from '@/lib/types';

const demoProfile: SleepProfile = { position:'side', weight:170, height:68, firmness:'medium', surfaceFeel:'medium', temperature:'hot', motion:'couple', priority:'pressure', budget:1500, types:['hybrid'] };

export default async function MattressPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const mattress = mattresses.find((item) => item.id === id);
  if (!mattress) return <main className="grid min-h-screen place-items-center bg-[#eef4f0] p-6"><div className="text-center"><h1 className="text-4xl font-extrabold">Mattress not found</h1><Link href="/" className="btn-primary mt-6 inline-flex">Back home <ArrowRight size={17}/></Link></div></main>;
  const score = scoreMattress(mattress, demoProfile);
  const metrics = [['Pressure relief',score.pressure],['Support & alignment',score.support],['Cooling',score.cooling],['Motion isolation',score.motion],['Edge support',score.edge],['Responsiveness',score.responsiveness]] as const;
  return <main className="min-h-screen bg-[#eef4f0] pb-24 pt-8 text-[#092e2a]">
    <header className="mx-auto flex max-w-[1240px] items-center justify-between px-6"><Link href="/" className="flex items-center gap-2 font-extrabold"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#092e2a] text-white">M</span> mattress match</Link><Link href="/mattresses" className="btn-secondary !px-4 !py-2.5 text-sm"><ArrowLeft size={15}/> All mattresses</Link></header>
    <section className="section pt-16"><div className="grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]">
      <div><span className="eyebrow">{mattress.brand} · {mattress.type}</span><h1 className="mt-4 text-6xl font-extrabold tracking-[-.06em] sm:text-8xl">{mattress.model}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#64736e]">A transparent look at how this mattress performs against a sample hot-sleeper, side-sleeper couple profile. Your actual score is recalculated from your own answers.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/#match" className="btn-primary">Get my personal match <ArrowRight size={17}/></Link><a href="#retailers" className="btn-secondary">See retailer options <ExternalLink size={16}/></a></div></div>
      <div className="relative overflow-hidden rounded-[36px] bg-[#d9e6e0] p-5 shadow-[0_30px_90px_rgba(8,48,42,.12)]"><img src={mattress.image} alt={`${mattress.brand} ${mattress.model}`} className="aspect-[4/3] w-full rounded-[26px] object-cover"/><div className="absolute bottom-10 left-10 rounded-3xl bg-white/95 p-5 shadow-xl backdrop-blur"><div className="text-xs font-bold uppercase tracking-[.14em] text-[#71807a]">Demo match</div><div className="mt-1 text-5xl font-extrabold">{score.overall}<span className="text-lg text-[#7a8883]">/100</span></div></div></div>
    </div></section>

    <section className="section mt-14"><div className="rounded-[38px] bg-[#092e2a] p-7 text-white sm:p-10"><div className="flex flex-wrap items-end justify-between gap-6"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#6ce7d6]">Match breakdown</span><h2 className="mt-3 text-4xl font-extrabold">Where it fits — and where it doesn&apos;t.</h2></div><div className="text-right"><div className="text-6xl font-extrabold text-[#6ce7d6]">{score.overall}</div><div className="text-xs uppercase tracking-[.15em] text-white/50">sample profile</div></div></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label,value])=><div key={label} className="rounded-2xl bg-white/8 p-5"><div className="flex justify-between text-sm"><span>{label}</span><b>{value}</b></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#6ce7d6]" style={{width:`${value}%`}}/></div></div>)}</div></div></section>

    <section className="section mt-14 grid gap-5 lg:grid-cols-3"><div className="rounded-[30px] bg-white p-7"><Layers3 className="text-[#18a895]"/><h2 className="mt-5 text-2xl font-extrabold">What&apos;s inside</h2><div className="mt-5 space-y-3">{mattress.materials.map((item)=><p key={item} className="flex gap-2 text-sm text-[#64736e]"><Check size={17} className="shrink-0 text-[#18a895]"/>{item}</p>)}</div></div><div className="rounded-[30px] bg-white p-7"><Wind className="text-[#18a895]"/><h2 className="mt-5 text-2xl font-extrabold">Cooling & feel</h2><p className="mt-4 text-sm leading-7 text-[#64736e]">Firmness: <b>{mattress.firmness}/10</b>. Cooling score: <b>{mattress.cooling}/100</b>. We surface cooling as a separate factor because comfort depends on the sleeper, not a universal star rating.</p></div><div className="rounded-[30px] bg-white p-7"><Moon className="text-[#18a895]"/><h2 className="mt-5 text-2xl font-extrabold">Trial & warranty</h2><p className="mt-4 text-sm leading-7 text-[#64736e]">{mattress.trial} trial · {mattress.warranty} warranty. Always confirm the current retailer terms before purchase.</p></div></section>

    <section className="section mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-[30px] bg-white p-7"><h2 className="text-2xl font-extrabold">Why it fits</h2><div className="mt-5 space-y-3">{score.reasons.map((reason)=><p key={reason} className="flex gap-3 text-sm leading-6 text-[#53645f]"><Check className="mt-1 shrink-0 text-[#18a895]" size={17}/>{reason}</p>)}</div></div><div className="rounded-[30px] bg-[#fff7e9] p-7"><h2 className="flex items-center gap-2 text-2xl font-extrabold text-[#765516]"><ShieldAlert size={22}/> Things to consider</h2><div className="mt-5 space-y-3">{(score.risks.length ? score.risks : mattress.risks).map((risk)=><p key={risk} className="text-sm leading-6 text-[#806c45]">{risk}</p>)}</div></div></section>

    <section id="retailers" className="section mt-14"><div className="rounded-[34px] border border-[#d5e0db] bg-white p-7 sm:p-10"><span className="eyebrow">Retailer options</span><h2 className="mt-3 text-4xl font-extrabold">Ready to check current availability?</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#64736e]">Retailer links are intentionally data-driven. No destination or affiliate URL is invented. Purchases may earn us a commission at no additional cost to you.</p><div className="mt-7 flex flex-wrap gap-3"><button type="button" disabled className="rounded-full bg-[#e9efec] px-5 py-3 text-sm font-bold text-[#8a9691]">Retailer link coming soon</button><Link href="/affiliate-disclosure" className="btn-secondary">Affiliate disclosure <ArrowRight size={16}/></Link></div></div></section>
  </main>;
}
