import Link from 'next/link';
import { ArrowDown, ArrowRight, Check, ShieldCheck, Sparkles } from 'lucide-react';
import { HeroMattress } from '@/components/hero-mattress';
import { MatchQuiz } from '@/components/match-quiz';
import { SiteFooter } from '@/components/site-footer';

const stats=[['01','Tell us how you sleep','Position, body profile, temperature and comfort priorities.'],['02','Score what actually matters','A versioned model turns your inputs into transparent fit signals.'],['03','See the tradeoffs clearly','Risks, strengths and review evidence stay visible.']];
const signals=[['Pressure relief',94],['Support & alignment',91],['Cooling',88],['Motion isolation',95]];

export default function Home(){return <main className="overflow-hidden bg-[#041311] text-white">
  <header className="fixed left-0 right-0 top-0 z-50"><div className="mx-auto mt-4 flex max-w-[1320px] items-center justify-between rounded-full border border-white/10 bg-[#061a17]/75 px-4 py-3 shadow-2xl shadow-black/30 backdrop-blur-2xl sm:px-6"><Link href="/" className="flex items-center gap-2.5 font-extrabold tracking-[-.04em]"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#19d8c1] text-[#041311] shadow-[0_0_25px_rgba(25,216,193,.35)]">M</span><span>mattress match</span></Link><nav className="hidden items-center gap-7 text-sm text-white/60 md:flex"><a href="#how" className="transition hover:text-white">How it works</a><a href="#match" className="transition hover:text-white">Find your match</a><Link href="/mattresses" className="transition hover:text-white">Mattresses</Link><Link href="/compare" className="transition hover:text-white">Compare</Link><Link href="/methodology" className="transition hover:text-white">Methodology</Link></nav><a href="#match" className="rounded-full bg-[#20d7c0] px-4 py-2.5 text-sm font-extrabold text-[#041311] shadow-[0_0_25px_rgba(32,215,192,.2)] transition hover:-translate-y-0.5 hover:bg-[#66f0dd]">Take the quiz <ArrowRight size={15} className="ml-1 inline"/></a></div></header>

  <section className="relative min-h-[900px] overflow-hidden border-b border-white/10 bg-[radial-gradient(circle_at_65%_35%,rgba(19,180,161,.18),transparent_30%),radial-gradient(circle_at_90%_15%,rgba(56,133,255,.13),transparent_25%),#041311] pt-28">
    <div className="pointer-events-none absolute left-[58%] top-20 h-[620px] w-[620px] -translate-x-1/2 rounded-full border border-[#1bd7c1]/15 shadow-[0_0_180px_rgba(24,183,162,.12)]"/><div className="pointer-events-none absolute -bottom-40 -left-20 h-[520px] w-[520px] rounded-full bg-[#1bd7c1]/10 blur-[120px]"/>
    <div className="section relative grid min-h-[770px] items-center gap-4 !py-16 lg:grid-cols-[.82fr_1.18fr]">
      <div className="relative z-10 max-w-xl"><div className="eyebrow !text-[#52ead8] flex items-center gap-2"><Sparkles size={13}/> Better sleep. A healthier you.</div><h1 className="mt-5 text-[clamp(3.5rem,7vw,7.4rem)] font-extrabold leading-[.86] tracking-[-.075em]">Find your <span className="bg-gradient-to-r from-white via-[#aaf8ed] to-[#19d8c1] bg-clip-text text-transparent">perfect</span> mattress match.</h1><p className="mt-7 max-w-lg text-base leading-7 text-white/55 sm:text-lg">A personalized mattress finder built around how you actually sleep—not generic star ratings.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#match" className="group rounded-full bg-[#20d7c0] px-6 py-3.5 font-extrabold text-[#041311] shadow-[0_14px_45px_rgba(25,216,193,.22)] transition hover:-translate-y-1 hover:bg-[#76f5e4]">Start your match <ArrowRight size={18} className="ml-1 inline transition group-hover:translate-x-1"/></a><a href="#how" className="rounded-full border border-white/15 bg-white/5 px-6 py-3.5 font-bold text-white/80 backdrop-blur transition hover:-translate-y-1 hover:border-white/30 hover:bg-white/10">How it works</a></div><div className="mt-10 grid max-w-lg grid-cols-3 gap-4 border-t border-white/10 pt-6 text-xs text-white/45"><div><b className="block text-white/80">Data driven</b>Structured inputs</div><div><b className="block text-white/80">Trusted sources</b>Review evidence</div><div><b className="block text-white/80">Clear tradeoffs</b>Risk flags</div></div></div>
      <div className="relative min-h-[560px] lg:min-h-[700px]"><div className="absolute inset-0 rounded-[50%] bg-[#19d8c1]/8 blur-[100px]"/><div className="relative h-full drop-shadow-[0_35px_80px_rgba(0,0,0,.5)]"><HeroMattress/></div><div className="absolute bottom-8 left-1/2 z-20 -translate-x-1/2 rounded-full border border-[#2be1cd]/50 bg-[#061a17]/75 px-5 py-3 text-xs font-bold text-[#9af8eb] backdrop-blur-xl shadow-[0_0_40px_rgba(25,216,193,.15)]"><span className="mr-2 inline-block h-2 w-2 animate-pulse rounded-full bg-[#2be1cd]"/> Better sleep starts here</div></div>
    </div><a href="#how" aria-label="Scroll to how it works" className="absolute bottom-7 left-1/2 grid -translate-x-1/2 place-items-center rounded-full border border-white/10 p-3 text-white/50 transition hover:border-white/30 hover:text-white"><ArrowDown size={18}/></a>
  </section>

  <section id="how" className="border-b border-white/10 bg-[#061a17]"><div className="section"><div className="grid gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><span className="eyebrow !text-[#52ead8]">The idea</span><h2 className="mt-4 text-5xl font-extrabold leading-[.92] tracking-[-.06em] sm:text-7xl">A mattress review should start with <span className="text-[#20d7c0]">you.</span></h2><p className="mt-7 max-w-md leading-7 text-white/45">We translate your sleep profile into a transparent Match Score, then show the strengths and compromises behind it.</p></div><div className="space-y-3">{stats.map(([n,t,d])=><div key={n} className="group rounded-[28px] border border-white/10 bg-white/[.035] p-6 transition duration-500 hover:-translate-y-1 hover:border-[#20d7c0]/40 hover:bg-white/[.06]"><div className="flex items-start gap-5"><span className="text-sm font-extrabold text-[#20d7c0]">{n}</span><div><h3 className="text-xl font-bold">{t}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-white/40">{d}</p></div><ArrowRight className="ml-auto mt-1 text-white/25 transition group-hover:translate-x-1 group-hover:text-[#20d7c0]"/></div></div>)}</div></div></div></section>

  <section id="match" className="relative overflow-hidden border-b border-white/10 bg-[#e9f0ed] text-[#061a17]"><div className="absolute right-[-15%] top-[-25%] h-[600px] w-[600px] rounded-full bg-[#20d7c0]/10 blur-[110px]"/><div className="section relative grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><span className="eyebrow">Your match</span><h2 className="mt-4 text-5xl font-extrabold leading-[.92] tracking-[-.06em] sm:text-7xl">Make it <span className="text-[#079d8a]">personal.</span></h2><p className="mt-6 max-w-md leading-7 text-[#52635e]">A few focused questions create your starting sleep profile. No account required to begin.</p><div className="mt-8 space-y-3 text-sm font-semibold text-[#344640]">{['Sleep position & body profile','Firmness & surface feel','Temperature & motion sensitivity','Comfort priority & budget'].map(x=><p key={x} className="flex items-center gap-3"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#d3f5ef] text-[#079d8a]"><Check size={14}/></span>{x}</p>)}</div></div><div className="depth-card overflow-hidden rounded-[34px] border border-white bg-white shadow-[0_30px_100px_rgba(6,26,23,.13)]"><MatchQuiz/></div></div></section>

  <section id="results" className="bg-[#041311]"><div className="section"><div className="grid gap-12 overflow-hidden rounded-[42px] border border-[#1bd7c1]/15 bg-[radial-gradient(circle_at_75%_20%,rgba(27,215,193,.12),transparent_30%),#071f1b] p-8 text-white sm:p-14 lg:grid-cols-[1fr_.82fr] lg:items-center"><div><span className="eyebrow !text-[#52ead8]">The score</span><h2 className="mt-4 text-5xl font-extrabold leading-[.92] tracking-[-.06em] sm:text-7xl">Scores with context, not hype.</h2><p className="mt-6 max-w-xl leading-7 text-white/45">See what fits, what does not, and why—with side-by-side comparisons, mapped review highlights and explicit risk flags.</p><Link href="/mattresses" className="mt-8 inline-flex rounded-full bg-[#20d7c0] px-6 py-3.5 font-extrabold text-[#041311] transition hover:-translate-y-1 hover:bg-[#76f5e4]">Explore mattresses <ArrowRight size={18} className="ml-2"/></Link></div><div className="rounded-[32px] border border-white/10 bg-white/[.06] p-7 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.16em] text-[#52ead8]">Example match</span><span className="rounded-full border border-[#20d7c0]/30 px-3 py-1 text-[10px] font-bold text-[#8df5e8]">PROFILE FIT</span></div><div className="mt-2 text-7xl font-extrabold tracking-[-.08em]">92<span className="text-2xl text-white/35">/100</span></div><div className="mt-6 space-y-4">{signals.map(([label,value])=><div key={label as string}><div className="mb-1.5 flex justify-between text-sm"><span className="text-white/65">{label}</span><b className="text-[#8df5e8]">{value}</b></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#0e8e7e] to-[#4df0dc]" style={{width:`${value}%`}}/></div></div>)}</div><div className="mt-6 rounded-2xl border border-[#20d7c0]/15 bg-[#20d7c0]/5 p-4 text-xs leading-5 text-white/45">Your score is a fit signal, not a universal rating. Every result keeps the assumptions and tradeoffs visible.</div></div></div></div></section>
  <SiteFooter/>
</main>}
