'use client';
import { useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import type { SleepProfile } from '@/lib/types';

const steps=[['position','How do you sleep?',['side','back','stomach','combination']],['weight','What is your weight range?',['<130','130–180','180–230','230+']],['firmness','What feel do you prefer?',['soft','medium','firm']],['temperature','How do you sleep temperature-wise?',['hot','neutral','cold']],['motion','Do you share your bed?',['single','couple']],['priority','What matters most?',['pressure','back','hips-shoulders','balanced']]] as const;
export function MatchQuiz(){const [i,setI]=useState(0);const [answers,setAnswers]=useState<Record<string,string>>({});const [done,setDone]=useState(false);const [selected,setSelected]=useState('');const step=steps[i];
 if(done)return <div className="rounded-[32px] bg-[#092e2a] p-8 text-white shadow-2xl sm:p-12"><span className="eyebrow !text-[#6ce7d6]">Profile complete</span><h3 className="mt-3 text-3xl font-bold">Your sleep profile is ready.</h3><p className="mt-3 max-w-xl text-white/65">We have enough signal to calculate a personalized match. Your preferences stay in this session.</p><a className="btn-primary mt-7 !bg-[#6ce7d6] !text-[#092e2a]" href="#results">See my matches <ArrowRight size={17}/></a></div>;
 const choose=(v:string)=>{setSelected(v);setAnswers(a=>({...a,[step[0]]:v}));};
 const next=()=>{if(!selected)return;if(i===steps.length-1)setDone(true);else{setI(i+1);setSelected(answers[steps[i+1][0]]||'')}};
 return <div className="rounded-[32px] border border-white/70 bg-white p-6 shadow-[0_25px_80px_rgba(10,45,40,.09)] sm:p-10"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.16em] text-[#178f80]">Quick match</span><span className="text-sm text-[#66706d]">{i+1} / {steps.length}</span></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-[#e5ece8]"><div className="h-full rounded-full bg-[#18b7a2] transition-all" style={{width:`${((i+1)/steps.length)*100}%`}}/></div><h3 className="mt-9 text-3xl font-bold">{step[1]}</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{step[2].map(v=><button key={v} onClick={()=>choose(v)} className={`flex min-h-14 items-center justify-between rounded-2xl border px-5 text-left transition ${selected===v?'border-[#18b7a2] bg-[#eaf9f6]':'border-[#dce4df] bg-white hover:-translate-y-0.5 hover:border-[#a9bbb5]'}`}><span className="capitalize">{v.replace('-',' / ')}</span>{selected===v&&<Check size={18} className="text-[#128f80]"/>}</button>)}</div><button onClick={next} disabled={!selected} className="btn-primary mt-7 w-full disabled:cursor-not-allowed disabled:opacity-40">{i===steps.length-1?'Calculate my match':'Continue'} <ArrowRight size={17}/></button></div>}
